apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: StatStrikeforce
  labels:
  role: app
spec:
  replicas: 1
  selector:
    matchLabels:
      role: app
  template:
    metadata:
      labels:
        role: app
    spec:
      containers:
      - name: backend-cont
        image: maxwellmendenhall/strike-force-tracker
        resources:
          requests:
            cpu: 10m
        ports:
        - containerPort: 3306
