apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
  role: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-deployment
  template:
    metadata:
      labels:
        app: backend-deployment
    spec:
      containers:
      - name: backend-cont
        image: maxwellmendenhall/strike-force-tracker:v1.0
        resources:
          requests:
            cpu: 10m
        env: 
        - name: SECRET_KEY
          value: your_secret_key
        - name: DATABASE
          value: path_to_your_database.db
        - name: UBI_EMAIL
          value: example@example.com
        - name: UBI_PASSWORD
          value: yourpassword
        ports:
        - containerPort: 3306
