apiVersion: apps/v1
kind: Deployment
metadata:
  name: machine-learning
  labels:
    role: app
spec:
  replicas: 2
  selector:
    matchLabels:
      role: app
  template:
    metadata:
      labels:
        role: app
    spec:
      containers:
      - name: machine-learning
        image: path/imagename:tag
        resources:
          requests:
            cpu: 10m
        ports:
        - containerPort: 80
