apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui-deployment
  labels:
  role: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webui-deployment
  template:
    metadata:
      labels:
        app: webui-deployment
    spec:
      containers:
      - name: webui-cont
        image: rsayre14/csc468:Web-UI
        resources:
          requests:
            cpu: 10m
        ports:
        - containerPort: 80
