apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui-deployment
  labels:
    role: app
spec:
  replicas: 2
  selector:
    matchLabels:
      role: app
  template:
    metadata:
      labels:
        role: app
    spec:
      containers:
      - name: webui-cont
        image: rsayre14/csc468:Web-UI
        resources:
          requests:
            cpu: 10m
        ports:
        - containerPort: 3306
