apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    role: app
spec:
  replicas: 2
  selector:
    matchLabels:
      role: app
  template:
    metadata:
      labels:
        role: app
    spec:
      containers:
      - name: backend
        image: rsayre14/csc468:Backend
        resources:
          requests:
            cpu: 10m
        env: 
        - name: SECRET_KEY
          value: your_secret_key
        - name: DATABASE
          value: path_to_your_database.db
        - name: UBI_EMAIL
          value: example@example.com
        - name: UBI_PASSWORD
          value: yourpassword
        ports:
        - containerPort: 80
