apiVersion: v1
kind: Service
metadata:
  name: webui-svc
  namespace: statstrikeforce
spec:
  selector:
    app: webui-deployment
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 8080
