apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: StatStrikeforce
spec:
  selector:
    app: backend-deployment
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
