apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  selector:
    app: backend-deployment
  type: NodePort
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
    nodePort: 33000
